services:
  backend:
    build:
      context: ./backend
    volumes:
      - ./backend:/var/www
    ports:
      - "8000:8000"
    networks:
      - app-network

  database:
    image: mysql:latest
    volumes:
      - db_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: simple-wallet
    ports:
      - "3306:3306"
    networks:
      - app-network

  frontend:
    build:
      context: ./frontend
    volumes:
      - ./frontend:/app
      - node_modules:/app/node_modules
    ports:
      - "3000:3000"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  db_data:
  node_modules:
